<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>TuringMorphogenesis3D</RootNamespace>
		<AssemblyName>TuringMorphogenesis3D</AssemblyName>
		<NoWarn>NU1701</NoWarn>
		<TieredPGO>true</TieredPGO>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="HelixToolkit.Wpf" Version="2.24.0" />
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
		<PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
		<PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
		<PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
		<PackageReference Include="NAudio" Version="2.2.1" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Shaders\RDCompute.hlsl">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>